# -*- coding: utf-8 -*-
"""sales data analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VsSqRrLZHo1O2YvOPv4hkgaw8oK2fCJr
"""

#Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Step 1: Load the dataset
df = pd.read_csv('/content/ECOMM DATA.xlsx - Orders.csv')

print(df.columns)

df.head()

df.tail()

df = df.fillna(0)  # Replace NaN values with 0

# Calculate Total Sales (adjusting for discount if necessary)
df['Total_Sales'] = df['Quantity'] * df['Sales'] * (1 - df['Discount'] / 100)

# Display Total Sales
total_sales = df['Total_Sales'].sum()
print(f"Total Sales: {total_sales}")

# Step 3: Analyze Sales Trends Over Time
# Convert the 'Order Date' column to datetime format
df['Order Date'] = pd.to_datetime(df['Order Date'])

# Extract Month and Year from 'Order Date'
df['Month'] = df['Order Date'].dt.month
df['Year'] = df['Order Date'].dt.year

#Group by Year and Month for sales trends
sales_trends = df.groupby(['Year', 'Month'])['Total_Sales'].sum()
print(sales_trends)

# Plot sales trends
sales_trends.unstack(level=0).plot(kind='line', figsize=(10, 6), title='Sales Trends Over Time')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.legend(title='Year')
plt.grid()
plt.show()

# Step 4: Determine Best-Selling Products
# Group by 'Product Name' and calculate total quantity sold
best_selling = df.groupby('Product Name')['Quantity'].sum().sort_values(ascending=False)
print("Best-Selling Products:")
print(best_selling.head(10))  # Display top 10 products

# Plot top 10 best-selling products
best_selling.head(10).plot(kind='bar', figsize=(10, 6), title='Top 10 Best-Selling Products')
plt.xlabel('Product Name')
plt.ylabel('Quantity Sold')
plt.grid()
plt.show()

